# Version of the configuration file
version: 5.0.1

# Icarus theme variant, can be "default" or "cyberpunk"
variant: default

# Path or URL to the website's logo
logo: https://avatars.githubusercontent.com/u/95597335

# Page metadata configurations
head:
    # URL or path to the website's icon
    favicon: https://avatars.githubusercontent.com/u/95597335

    # Web Manifest Data
    manifest:
        # Name of the web application (default to the site title)
        name: skyclouds2001's blog
        # The displayed name of the web application
        # when there is not enough space to display full name
        short_name: sky
        # The start URL of the web application
        start_url: https://skyclouds2001.github.io/
        # The default theme color for the application
        theme_color: "#3273dc"
        # A placeholder background color for the application page to display
        # before its stylesheet is loaded
        background_color: "#3273dc"
        # The preferred display mode for the website
        display: standalone
        # Image files that can serve as application icons for different contexts
        icons:
            -
                # The path to the image file
                src: https://avatars.githubusercontent.com/u/95597335
                # A string containing space-separated image dimensions
                sizes: 460x460
                # A hint as to the media type of the image (optional)
                type: image/png

    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title: skyclouds2001's blog
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url: https://skyclouds2001.github.io/
        # Page cover (og:image) (optional)
        # You should leave this blank for most of the time
        image: https://avatars.githubusercontent.com/u/95597335
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name: skyclouds2001's blog
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: skyclouds2001
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description: The personal blog of skyclouds2001
        # Twitter card type (twitter:card)
        twitter_card:
        # Twitter ID (twitter:creator)
        twitter_id:
        # Twitter Site (twitter:site)
        twitter_site:
        # Google+ profile link (deprecated)
        google_plus:
        # Facebook admin ID
        fb_admins:
        # Facebook App ID
        fb_app_id:

    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title: skyclouds2001's blog
        # Page description (optional)
        # You should leave this blank for most of the time
        description: The personal blog of skyclouds2001
        # Page URL (optional)
        # You should leave this blank for most of the time
        url: https://skyclouds2001.github.io/
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: skyclouds2001
        # Page images (optional)
        # You should leave this blank for most of the time
        image: https://avatars.githubusercontent.com/u/95597335

    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - 'name=theme-color;content=#3273dc'

    # URL or path to the website's RSS atom.xml
    rss: /atom.xml

# Page top navigation bar configurations
navbar:
    # Naviagtion menu items
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
        Album: /album
        Friend: /friend
        Message: /message
        Self-talking: /self-talking
        Music: /music
        Media: /media
    # Links to be shown on the right of the navigation bar
    links:
        GitHub:
            icon: fab fa-github
            url: 'https://github.com/skyclouds2001/skyclouds2001.github.io/'

# Page footer configurations
footer:
    copyright: Copyright © 2022-present skyclouds2001
    # Links to be shown on the right of the footer section
    links:
        License:
            icon: fab fa-creative-commons
            url: 'https://mit-license.org/'
        GitHub:
            icon: fab fa-github
            url: 'https://github.com/skyclouds2001/skyclouds2001.github.io/'

# Article related configurations
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show estimated article reading time
    readtime: true
    # Article updating time
    update_time: true
    # Article licensing block
    licenses:
        License:
            icon: fab fa-creative-commons
            url: 'https://mit-license.org/'

# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight
    include_pages: true

# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
    type: gitalk
    # (required) OAuth application client id
    client_id: 5ff192d081aaca9c87bc
    # (required) OAuth application client secret
    client_secret: c42e1169d791a5b73eafe6fc8023efdbd3eb38ff
    # (required) GitHub repository name
    repo: skyclouds2001
    # (required) GitHub user name
    owner: skyclouds2001
    #Localization language key, en, zh-CN and zh-TW are currently available.
    language: zh-CN
    admin: ['skyclouds2001']
    per_page: 10
    distraction_free_mode: false
    pager_direction: last
    create_issue_manually: true
    proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token
    enable_hotkey: true
    # todo unknown properties
    has_hot_recommend: true # 是否有热门推荐
    has_latest_comment: true #是否有最新评论

# Donate plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donates:
    # Alipay donate button configurations
    -
        # Donation entry name
        type: alipay
        # Qrcode image URL
        qrcode: /images/alipay.jpg
    # Patreon donate button configurations
    -
        type: patreon
        # URL to the Patreon page
        url: https://www.patreon.com/user?u=105708204
    # WeChat donate button configurations
    -
        type: wechat
        # Wechat qrcode image URL
        qrcode: /images/wechat.png

# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share:
    type: sharejs

# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false

# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Table of contents widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: toc
        # Select show index
        index: true

    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: skyclouds2001
        # Author title
        author_title: 总有奋不顾身的相信，总要坚韧恒久的勇气
        # Author's current location
        location: China
        # URL or path to the avatar image
        avatar: https://avatars.githubusercontent.com/u/95597335
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar:
        # URL or path for the follow button
        follow_link: 'https://github.com/skyclouds2001'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/skyclouds2001'
            Email:
                icon: fa fa-envelope
                url: 'mailto:skyclouds2001@163.com'
            Blog:
                icon: fab fa-dribbble
                url: 'https://skyclouds2001.github.io/'
            RSS:
                icon: fas fa-rss
                url: /atom.xml
        # todo - unknown setting
        has_hitokoto: true

    # Recommendation links widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: links
        # Names and URLs of the sites
        links:
            Hexo: 'https://hexo.io'
            Icarus: 'https://github.com/ppoffice/hexo-theme-icarus'
            Amazing: 'https://github.com/removeif/hexo-theme-amazing'

    # Latest comment widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: latest_comment

    # Recent posts widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: recent_posts

    # Categories widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: categories

    # Archives widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: archives

    # Tags widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: tags
        # Order by tag name or length. Prefix with `-` to sort in descending order.
        order_by: name
        # The maximum number of tags to show. Leave empty to show all.
        amount: 20
        # Whether to show post count right to tag name.
        show_count: true

    # Google AdSense unit configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: adsense
        client_id: ca-pub-6540459960525651
        slot_id: 3012941103

    # Follow.it email subscription configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: followit
        description:
        action_url: https://api.follow.it/subscription-form/VUJhY1Y3Q05Ha3pvS3RzZDYrcWlRc1JTNGZQTEx5QXh4Z1llTmRtbHFDcy85allmd3hzWHkxcTc4dUFyNEhmQTkxQlZpL2JXdVQyeFVkY1pGaWNJY0ZLM0h4eGtyc0NnNlB3N2FvRnBxN1F1YVBLMkxmVHMweFlnZm1tWUorUXJ8UFBRMzljRXAyT3Nkd2NwK1VIei9RajZieHppdUVudEYzOGpIazh0bnBVZz0=/8
        verification_code: savxwnjFRLRWr4EYrhLa

# AdSense client ID
adsense_client_id: ca-pub-6540459960525651
# AdSense AD unit ID
adsense_slot_id: 3012941103
# article head ad
article_head_has_ad: true
# comment head ad
comment_head_has_ad: true
# other ad
index_zero_position_ad: true
# ad put position
index_ad_positions: 2,5,9

# Plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # Enable the lightGallery and Justified Gallery plugins
    # https://www.lightgalleryjs.com/
    # https://miromannino.github.io/Justified-Gallery/
    gallery: true
    # Enable the KaTeX math typesetting support
    # https://katex.org/
    katex: false
    # Enable the MathJax math typesetting support
    # https://www.mathjax.org/
    mathjax: false
    # Enable the cookie consent support
    # https://www.osano.com/cookieconsent
    cookie_consent:
        # The compliance type. Can be "info", "opt-in", or "opt-out"
        type: info
        # Theme of the popup. Can be "block", "edgeless", or "classic"
        theme: edgeless
        # Whether the popup should stay static regardless of the page scrolls
        static: false
        # Where on the screen the consent popup should display
        position: bottom-left
        # URL to your site's cookie policy
        policyLink: 'https://www.cookiesandyou.com/'
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated_browser: false
    # Enable page startup animations
    animejs: true
    # Show a progress bar at top of the page on page loading
    progressbar: true

    ## unknown
    # Show the "back to top" button
    back_to_top: true

    # Baidu Analytics plugin settings
    # https://tongji.baidu.com
    baidu_analytics:
        # Baidu Analytics tracking ID
        tracking_id: 98608f7861aa9247199463aaae2cffb9
    # Bing Webmaster Tools settings
    # https://www.bing.com/webmasters
    bing_webmaster:
        tracking_id: F334E8AF334D26B39D41AF73E58A98AC
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: true
    # Google Analytics plugin settings
    # https://analytics.google.com
    google_analytics:
        # Google Analytics tracking ID
        tracking_id: G-257NZ7S1BB

# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL template of the webfont CDN provider
    fontcdn: google
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: fontawesome

# footer 版权说明 可自由配置
footer_copyright_dsec: © 版权说明：[本网站所有内容均收集于互联网或自己创作,<br />&nbsp;&nbsp;&nbsp;&nbsp;方便于网友与自己学习交流，如有侵权，请<a href="/message" target="_blank">留言</a>，立即处理]<br />

# 网站运行开始时间,不填不显示
website_start_time: 2022/06/20 00:00:00

# 备案号
footer_registered_no: 浙ICP备88888888号-8

# 侧边栏网易云歌单id
side_music_netease_id: 4368985

# todo update config
busuanzi_only_count: false #当上面plugins中busuanzi: true时，此配置busuanzi_only_count为true时，网站不显示不蒜子统计数据，但是会每次统计。false时显示统计数据。
has_live_2D_switch: true #live2D开关 true-开 false-关
use_pjax: true #是否pjax
